
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qulefzbfnlvpgbqwjrka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1bGVmemJmbmx2cGdicXdqcmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTY0MjksImV4cCI6MjA1OTE3MjQyOX0.qdpD1hSIwD-_OB2Bc0ozY9eraKcoycXeBAP_d9Wc_rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
